### ISSUE TITLE
Creating a class diagram

### ISSUE THREAD

**Issue by lachimollala** [Intro-to-SE-Lab-Fall-20/Group-6#12]
For Sprint 2, we are required to have a class diagram to showcase the design and architecture for this project

**Comment by Justin-Paulk** [comment]
![Class_Diagram](https://user-images.githubusercontent.com/55258185/94302998-c5c9b600-ff32-11ea-9a72-5ba4dd7457a8.png)

**Comment by Justin-Paulk** [comment]
This is the class diagram for our users class. It is currently the only class in our backend code.

**Comment by Justin-Paulk** [comment]
The diagram has been added to the Class Diagrams wiki page
