### ISSUE TITLE
Creating a sequence diagram

### ISSUE THREAD

**Issue by lachimollala** [Intro-to-SE-Lab-Fall-20/Group-6#13]
For Sprint 2, we are required to have a sequence diagram to showcase the design and architecture for this project

**Comment by Mar744-dev** [comment]
[Intro to SE sequence diagrams.zip](https://github.com/Intro-to-SE-Lab-Fall-20/Group-6/files/5285870/Intro.to.SE.sequence.diagrams.zip)
Sequence Diagrams for Seec-mail
